import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

class PdfService {
  static Future<void> generateAndShareAnalyticsReport({
    required String revenue,
    required String orders,
    required String avgOrder,
    required List<Map<String, dynamic>> topItems,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('MY Cafe Analytics', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.brown900)),
                    pw.Text(DateTime.now().toString().split(' ')[0], style: const pw.TextStyle(color: PdfColors.grey)),
                  ],
                ),
                pw.Divider(thickness: 2, color: PdfColors.brown),
                pw.SizedBox(height: 40),
                
                pw.Text('Performance Summary', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 10),
                pw.TableHelper.fromTextArray(
                  border: pw.TableBorder.all(color: PdfColors.grey300),
                  headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                  headerDecoration: const pw.BoxDecoration(color: PdfColors.brown),
                  data: [
                    ['Metric', 'Value'],
                    ['Total Revenue', revenue],
                    ['Total Orders', orders],
                    ['Average Order Value', avgOrder],
                  ],
                ),
                pw.SizedBox(height: 40),
                
                pw.Text('Best Selling Products', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 10),
                pw.TableHelper.fromTextArray(
                  border: pw.TableBorder.all(color: PdfColors.grey300),
                  headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                  headerDecoration: const pw.BoxDecoration(color: PdfColors.brown800),
                  headers: ['Rank', 'Item Name', 'Revenue'],
                  data: topItems.map((item) => [
                    item['rank'].toString(),
                    item['name'].toString(),
                    item['revenue'].toString(),
                  ]).toList(),
                ),
                
                pw.Spacer(),
                pw.Divider(color: PdfColors.grey),
                pw.Align(
                  alignment: pw.Alignment.centerRight,
                  child: pw.Text('Generated by BrewDesk Cafe Management System', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                ),
              ],
            ),
          );
        },
      ),
    );

    final bytes = await pdf.save();
    final xfile = XFile.fromData(bytes, mimeType: 'application/pdf', name: 'cafe_analytics_${DateTime.now().millisecondsSinceEpoch}.pdf');
    await Share.shareXFiles([xfile], text: 'MY Cafe Performance Report');
  }
}
